### ISSUE TITLE
TypeScript complains about missing type declarations.

### ISSUE THREAD

**Issue by meh** [zyxd/svelte-store-router#1]
```
src/stores.ts(1,34): error TS2307: Cannot find module 'svelte-store-router' or its corresponding type declarations.
```

Am I doing something wrong?

**Comment by zyxd** [comment]
> ```
> src/stores.ts(1,34): error TS2307: Cannot find module 'svelte-store-router' or its corresponding type declarations.
> ```
> 
> 
> Am I doing something wrong?

Hello. Added a simple typescript definition file in v1.0.14, please check again.

_P.S. Not a TypeScript expert, would be great if someone can help. Does it make sense to rewrite the whole package on it?_

**Comment by meh** [comment]
Yeah, it seems to not be complaining anymore. Personally I prefer to use TypeScript if I have a choice, and there's no need to rewrite, TypeScript is designed to be able to incrementally add types and such :panda_face:
