### ISSUE TITLE
Update URL on new assignment to $route.path

### ISSUE THREAD

**Issue by jacob-8** [zyxd/svelte-store-router#2]
When using `<a href="/users">users</a>` the URL is changed accordingly, but not when using `<button on:click={() => ($route.path = '/users')}>user list</button>`. I'm not sure if this is an oversight, or by design, but it makes this tool very confusing to get up and running with. Consider changing your documentation to something like `<button on:click={() => (window.location.assign('/users'))}>user list</button>` instead or update the code to change url on assingments to $route.path in the same manner as you do for $route.query... and fragment.

**Comment by zyxd** [comment]
> When using `<a href="/users">users</a>` the URL is changed accordingly, but not when using `<button on:click={() => ($route.path = '/users')}>user list</button>`. I'm not sure if this is an oversight, or by design, but it makes this tool very confusing to get up and running with. Consider changing your documentation to something like `<button on:click={() => (window.location.assign('/users'))}>user list</button>` instead or update the code to change url on assingments to $route.path in the same manner as you do for $route.query... and fragment.

You are completely correct, the location should have changed on $route.path value assignment. Could you please check again in >= v1.0.13?

**Comment by jacob-8** [comment]
> You are completely correct, the location should have changed on $route.path value assignment. Could you please check again in >= v1.0.13?

It works as expected now. 

I have a new problem that many others have had in the past: https://github.com/sveltejs/svelte/issues/3165, when using the <Match> component with components inside the slot, related to your bumping the version of svelte from "^3.29.4" to "^3.31.0" - but I don't know if it's your problem to fix... It looks like a long standing challenge where 3rd-party packages also import Svelte. I need to learn more about [peerdependencies](https://nodejs.org/en/blog/npm/peer-dependencies/) to see if that is where a possible solution lies.

**Comment by zyxd** [comment]
> I have a new problem that many others have had in the past: [sveltejs/svelte#3165](https://github.com/sveltejs/svelte/issues/3165), when using the component with components inside the slot, related to your bumping the version of svelte from "^3.29.4" to "^3.31.0" - but I don't know if it's your problem to fix... It looks like a long standing challenge where 3rd-party packages also import Svelte. I need to learn more about [peerdependencies](https://nodejs.org/en/blog/npm/peer-dependencies/) to see if that is where a possible solution lies.

Can you make issue and reproduce this problem please? I caught this bug some time ago and somehow solved it... but now can't reproduce.
